### ISSUE TITLE
Cant sync work tree

### ISSUE THREAD

**Issue by Yaznas** [GZOSP/manifest#1]
I can't repo sync!

`Syncing work tree:  40% (240/600)  fatal: This operation must be run in a work tree
Traceback (most recent call last):
  File "/home/yaznas/gzosp/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/home/yaznas/gzosp/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/home/yaznas/gzosp/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/yaznas/gzosp/.repo/repo/subcmds/sync.py", line 821, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/home/yaznas/gzosp/.repo/repo/project.py", line 1327, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/home/yaznas/gzosp/.repo/repo/project.py", line 2486, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
`
Sorry! Issue Solved!

**Comment by TheRingMaster** [comment]
Np had to do a lil work to it for roomservice activation

**Comment by ankitk01** [comment]
how u solved it ??
